import {describe,expect,it} from "vitest";
import {buildStrategyCandidates,percentileRank,strategyExitDecision} from "./options-strategy-engine.mjs";

const expiry=Date.now()+14*86_400_000;
function contract(optionType,strike,delta,bid=.02,ask=.021){return{instrumentName:`BTC-X-${strike}-${optionType==="call"?"C":"P"}`,expirationTimestamp:expiry,dte:14,strike,optionType,tickSize:.0001,minTradeAmount:.1,bid,ask,spreadPct:(ask-bid)/((ask+bid)/2)*100,markIv:70,openInterest:100,greeks:{delta}};}
const snapshot={currency:"BTC",indexPrice:100_000,contracts:[contract("put",85_000,-.08),contract("put",90_000,-.18),contract("put",95_000,-.35),contract("put",100_000,-.5),contract("call",100_000,.5),contract("call",105_000,.35),contract("call",110_000,.18),contract("call",115_000,.08)]};
const config={enabledStrategies:["IRON_CONDOR","VERTICAL_DEBIT_SPREAD","LONG_STRADDLE"],minimumIvObservations:5,maxDefinedRiskUsd:10_000};
describe("options strategy policy engine",()=>{
 it("computes a deterministic IV percentile",()=>expect(percentileRank([40,50,60,70],60)).toBe(75));
 it("builds a four-leg defined-risk condor at target deltas",()=>{const candidate=buildStrategyCandidates({currency:"BTC",snapshot,ivHistory:[40,45,50,55,60],decision:{score:50,atrPct:.5,momentum4BarsPct:.1},config}).find(item=>item.id==="IRON_CONDOR");expect(candidate.plan.legs).toHaveLength(4);expect(candidate.plan.maxLossUsd).toBeGreaterThan(0);expect(candidate.blockers).not.toContain("NAKED_TAIL_RISK_BLOCKED");});
 it("calculates the short-straddle hedge recommendation but keeps routing blocked",()=>{const candidate=buildStrategyCandidates({currency:"BTC",snapshot,ivHistory:[40,45,50,55,60],decision:{score:50,atrPct:.5,momentum4BarsPct:.1},config:{...config,enabledStrategies:["SHORT_STRADDLE_HEDGED"]}}).find(item=>item.id==="SHORT_STRADDLE_HEDGED");expect(Number.isFinite(candidate.plan.recommendedHedgeUsd)).toBe(true);expect(candidate.executionEligible).toBe(false);expect(candidate.blockers).toContain("DELTA_HEDGE_EXECUTOR_NOT_ARMED");});
 it("does not label a cash-settled short call as physically covered",()=>{const candidate=buildStrategyCandidates({currency:"BTC",snapshot,ivHistory:[40,45,50,55,60],decision:{score:60,atrPct:.5,momentum4BarsPct:.1},config:{...config,enabledStrategies:["COLLATERAL_CALL"]}}).find(item=>item.id==="COLLATERAL_CALL");expect(candidate.executionEligible).toBe(false);expect(candidate.blockers).toContain("CASH_SETTLED_COVER_NOT_PROVEN");});
 it("requires an event or low-volatility squeeze for a long straddle",()=>{const candidate=buildStrategyCandidates({currency:"BTC",snapshot,ivHistory:[40,45,50,55,60],decision:{score:50,atrPct:.5,momentum4BarsPct:.1},config}).find(item=>item.id==="LONG_STRADDLE");expect(candidate.blockers).toContain("EVENT_OR_VOLATILITY_SQUEEZE_REQUIRED");});
 it("builds a directional debit spread only for a strong trend",()=>{const candidate=buildStrategyCandidates({currency:"BTC",snapshot,ivHistory:[40,45,50,55,60],decision:{score:85,atrPct:1,momentum4BarsPct:1},config}).find(item=>item.id==="VERTICAL_DEBIT_SPREAD");expect(candidate.plan.legs).toHaveLength(2);expect(candidate.plan.direction).toBe("bullish");expect(candidate.blockers).not.toContain("STRONG_DIRECTIONAL_SIGNAL_REQUIRED");});
 it("exits condors on a short-strike breach",()=>expect(strategyExitDecision({strategy:{strategyId:"IRON_CONDOR",shortStrikes:[90_000,110_000],maxProfitUsd:20,maxLossUsd:80},pnlUsd:0,spot:111_000,ageHours:2,maxStrategyHours:48})).toBe("SHORT_STRIKE_BREACH"));
 it("trails an armed long straddle at the portfolio level",()=>expect(strategyExitDecision({strategy:{strategyId:"LONG_STRADDLE",entryValueUsd:100,maxLossUsd:100,peakPnlUsd:40},pnlUsd:30,spot:100_000,ageHours:2,maxStrategyHours:48})).toBe("PORTFOLIO_TRAILING_PROFIT"));
 it("takes 80% of vertical maximum profit",()=>expect(strategyExitDecision({strategy:{strategyId:"VERTICAL_DEBIT_SPREAD",maxProfitUsd:100,maxLossUsd:50,planDirection:"bullish"},pnlUsd:80,spot:100_000,signal:{action:"BUY_CALL"},ageHours:2,maxStrategyHours:48})).toBe("EIGHTY_PERCENT_MAX_PROFIT"));
});
