"use client";
import { useCallback, useEffect, useState } from "react";
import { Activity, Bot, BrainCircuit, CircleStop, Clock3, RefreshCw, ShieldCheck, Zap } from "lucide-react";
import { Badge, Progress, SectionTitle } from "./ui";
import { cn } from "@/lib/utils";

type Config={enabled:boolean;currencies:("BTC"|"ETH")[];minimumScore:number;maxPremiumUsd:number;maxDailyTrades:number;cooldownMinutes:number;stopLossPct:number;takeProfitPct:number};
type Decision={currency:string;action:string;score:number;price?:number;rsi?:number;ema20?:number;ema50?:number;atrPct?:number;risk:string;executionEligible:boolean};
type Status={environment:string;config:Config;state:{workerOnline:boolean;enabled?:boolean;exitManagementActive?:boolean;lastHeartbeat?:string;lastEvaluation?:string;nextEvaluation?:string;decisions?:Decision[];positionCount?:number;openOrderCount?:number;tradesToday?:unknown[];error?:string|null};journal:Record<string,unknown>[];safety:{productionRoutingAvailable:boolean;executionEnvironmentLocked:boolean;serverExecutionGate:boolean}};

async function request<T>(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{"Content-Type":"application/json"}});const body=await response.json();if(!response.ok)throw new Error(body.error??"Request failed");return body as T;}
export function AutobotCockpit(){
 const [status,setStatus]=useState<Status|null>(null),[draft,setDraft]=useState<Config|null>(null),[message,setMessage]=useState(""),[confirmation,setConfirmation]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const next=await request<Status>("/api/v1/autobot/status");setStatus(next);setDraft(current=>current??next.config);}catch(error){setMessage(error instanceof Error?error.message:"Worker unavailable");}},[]);
 useEffect(()=>{const initial=setTimeout(()=>void load(),0),timer=setInterval(()=>void load(),5_000);return()=>{clearTimeout(initial);clearInterval(timer);};},[load]);
 async function save(){if(!draft)return;setBusy(true);try{await request("/api/v1/autobot/config",{method:"POST",body:JSON.stringify({...draft,enabled:false})});setMessage("Risk policy saved. Autonomous routing remains disabled.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Unable to save");}finally{setBusy(false);}}
 async function halt(){setBusy(true);try{await request("/api/v1/autobot/halt",{method:"POST"});setMessage("New entries paused. Existing bot-owned positions remain under automatic exit management.");await load();}finally{setBusy(false);}}
 async function activate(){if(!draft)return;setBusy(true);try{await request("/api/v1/autobot/config",{method:"POST",body:JSON.stringify({...draft,enabled:true,confirmation})});setMessage("Deribit Testnet autonomous routing armed. The worker will act only when signal and every risk gate pass.");setConfirmation("");await load();}catch(error){setMessage(error instanceof Error?error.message:"Activation rejected");}finally{setBusy(false);}}
 if(!status||!draft)return <div className="panel flex h-80 items-center justify-center rounded-lg text-slate-500"><RefreshCw className="mr-2 size-4 animate-spin"/>Connecting to autonomous worker…</div>;
 const decisions=status.state.decisions??[];const active=Boolean(status.state.workerOnline&&status.state.enabled);
 return <div className="space-y-5">
  <section className="flex flex-col justify-between gap-4 border-b border-line/60 pb-5 xl:flex-row xl:items-end"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-semibold">Autonomous Trading AI</h2><Badge tone={status.state.workerOnline?"positive":"negative"}>{status.state.workerOnline?"WORKER ONLINE":"WORKER OFFLINE"}</Badge><Badge tone={active?"positive":"warning"}>{active?"AUTONOMOUS · TESTNET":"NEW ENTRIES PAUSED"}</Badge>{status.state.exitManagementActive&&<Badge tone="positive">EXITS MANAGED</Badge>}</div><p className="mt-2 max-w-3xl text-[11px] text-slate-500">Explainable regime engine scans completed 15-minute BTC/ETH candles, selects limited-loss long options, and enforces premium, position, cooldown and daily-trade caps.</p></div><button onClick={halt} disabled={busy||!active} className="flex items-center justify-center gap-2 rounded border border-coral/30 bg-coral/10 px-5 py-2.5 text-[10px] font-semibold text-coral disabled:opacity-30"><CircleStop className="size-4"/>PAUSE NEW ENTRIES</button></section>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Bot} label="Engine mode" value={active?"AUTONOMOUS":"MONITOR"} meta="Deribit Testnet only" positive={active}/><Metric icon={Activity} label="Managed positions" value={String(status.state.positionCount??0)} meta={`${status.state.openOrderCount??0} resting bot orders`}/><Metric icon={Zap} label="Trades today" value={String(status.state.tradesToday?.length??0)} meta={`cap ${draft.maxDailyTrades} per day`}/><Metric icon={Clock3} label="Last evaluation" value={status.state.lastEvaluation?new Date(status.state.lastEvaluation).toLocaleTimeString():"Waiting"} meta="completed 15m candles"/></div>
  <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="panel rounded-lg p-5"><SectionTitle eyebrow="Explainable decisions" title="Live Signal Matrix" action={<Badge tone="positive">No black box</Badge>}/><div className="grid gap-3 md:grid-cols-2">{decisions.map(item=><div key={item.currency} className="rounded-lg border border-line bg-black/15 p-4"><div className="flex items-start justify-between"><div><div className="text-lg font-semibold">{item.currency}</div><div className="font-mono text-[9px] text-slate-600">${item.price?.toLocaleString()??"—"}</div></div><Badge tone={item.action==="BUY_CALL"?"positive":item.action==="BUY_PUT"?"negative":"warning"}>{item.action.replace("_"," ")}</Badge></div><div className="mt-5 flex items-end justify-between"><div><div className="font-mono text-3xl font-semibold">{item.score}</div><div className="text-[8px] uppercase text-slate-600">confidence score</div></div><div className="text-right font-mono text-[9px] text-slate-500">RSI {item.rsi?.toFixed(1)??"—"}<br/>ATR {item.atrPct?.toFixed(2)??"—"}%</div></div><div className="mt-3"><Progress value={item.score} tone={item.score>=draft.minimumScore?"mint":item.score<=100-draft.minimumScore?"coral":"amber"}/></div><div className="mt-4 flex items-center justify-between border-t border-line pt-3 text-[9px]"><span className="text-slate-600">Risk gate</span><span className={item.executionEligible?"text-mint":"text-amber"}>{item.risk}</span></div></div>)}</div>{decisions.length===0&&<div className="py-16 text-center text-xs text-slate-600">Waiting for first evaluation cycle</div>}</section>
  <section className="panel rounded-lg p-5"><SectionTitle eyebrow="Fail-closed policy" title="Safety Boundary"/><div className="space-y-3"><Safety label="Environment hard lock" value="DERIBIT TESTNET"/><Safety label="Production routing" value="NOT PRESENT"/><Safety label="Instrument exposure" value="LONG OPTIONS ONLY"/><Safety label="Maximum positions" value="1 PER CURRENCY"/><Safety label="Stale order policy" value="IOC / CANCEL"/><Safety label="Server execution gate" value={status.safety.serverExecutionGate?"ARMED":"LOCKED"} good={status.safety.serverExecutionGate}/></div><div className="mt-4 rounded border border-amber/20 bg-amber/5 p-3 text-[9px] leading-relaxed text-amber">The worker is installed in monitoring mode. Activation requires a separate server flag and explicit phrase after validation.</div></section></div>
  <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><section className="panel rounded-lg p-5"><SectionTitle eyebrow="Autonomous policy" title="Risk Controls" action={<Badge tone={active?"warning":"positive"}>{active?"LOCKED WHILE ACTIVE":"EDITABLE"}</Badge>}/><div className="grid grid-cols-2 gap-3"><Field label="Minimum score"><input disabled={active} value={draft.minimumScore} type="number" onChange={e=>setDraft({...draft,minimumScore:+e.target.value})}/></Field><Field label="Premium cap USD"><input disabled={active} value={draft.maxPremiumUsd} type="number" onChange={e=>setDraft({...draft,maxPremiumUsd:+e.target.value})}/></Field><Field label="Trades / day"><input disabled={active} value={draft.maxDailyTrades} type="number" onChange={e=>setDraft({...draft,maxDailyTrades:+e.target.value})}/></Field><Field label="Cooldown minutes"><input disabled={active} value={draft.cooldownMinutes} type="number" onChange={e=>setDraft({...draft,cooldownMinutes:+e.target.value})}/></Field><Field label="Stop loss %"><input disabled={active} value={draft.stopLossPct} type="number" onChange={e=>setDraft({...draft,stopLossPct:+e.target.value})}/></Field><Field label="Take profit %"><input disabled={active} value={draft.takeProfitPct} type="number" onChange={e=>setDraft({...draft,takeProfitPct:+e.target.value})}/></Field></div><button onClick={save} disabled={busy||active} className="mt-4 w-full rounded border border-line px-4 py-2.5 text-[10px] font-semibold disabled:opacity-40">{active?"POLICY LOCKED · BOT ACTIVE":"SAVE POLICY · PAUSE NEW ENTRIES"}</button>{status.safety.serverExecutionGate&&!active&&<div className="mt-4 border-t border-line pt-4"><Field label="Type ENABLE DERIBIT TESTNET AUTOBOT"><input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></Field><button onClick={activate} disabled={busy||confirmation!=="ENABLE DERIBIT TESTNET AUTOBOT"} className="mt-3 w-full rounded bg-mint px-4 py-2.5 text-[10px] font-semibold text-black disabled:opacity-30">ACTIVATE AUTONOMOUS TESTNET</button></div>}</section>
  <section className="panel overflow-hidden rounded-lg"><div className="border-b border-line px-5 py-4"><SectionTitle eyebrow="Immutable local journal" title="Decision & Execution Audit" action={<BrainCircuit className="size-4 text-mint"/>}/></div><div className="max-h-[360px] overflow-auto divide-y divide-line/50">{status.journal.slice(0,20).map((event,index)=><div key={index} className="grid grid-cols-[140px_1fr_auto] gap-3 px-5 py-3 font-mono text-[9px]"><span className="text-slate-600">{event.timestamp?new Date(String(event.timestamp)).toLocaleString():"—"}</span><span>{String(event.type??"EVENT").replaceAll("_"," ")}</span><span className="text-slate-600">{String(event.currency??event.message??"").slice(0,40)}</span></div>)}{status.journal.length===0&&<div className="p-10 text-center text-xs text-slate-600">Journal is empty</div>}</div></section></div>
  {(message||status.state.error)&&<div className={cn("rounded border p-3 text-[10px]",status.state.error?"border-coral/30 text-coral":"border-mint/20 text-mint")}>{status.state.error??message}</div>}
 </div>;
}
function Metric({icon:Icon,label,value,meta,positive}:{icon:typeof Bot;label:string;value:string;meta:string;positive?:boolean}){return <div className="panel rounded-lg p-4"><div className="flex justify-between text-[9px] uppercase text-slate-600">{label}<Icon className={cn("size-4",positive?"text-mint":"text-slate-600")}/></div><div className="mt-4 font-mono text-xl font-semibold">{value}</div><div className="mt-1 font-mono text-[8px] text-slate-600">{meta}</div></div>}
function Safety({label,value,good=true}:{label:string;value:string;good?:boolean}){return <div className="flex items-center justify-between rounded border border-line p-3 text-[9px]"><span className="text-slate-600">{label}</span><span className={good?"text-mint":"text-amber"}><ShieldCheck className="mr-1 inline size-3"/>{value}</span></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-[8px] uppercase text-slate-600">{label}<div className="mt-1 [&_input]:w-full [&_input]:rounded [&_input]:border [&_input]:border-line [&_input]:bg-black/20 [&_input]:p-2 [&_input]:font-mono [&_input]:text-[10px] [&_input]:text-white [&_input:disabled]:cursor-not-allowed [&_input:disabled]:opacity-40">{children}</div></label>}
