"use client";
import { useCallback,useEffect,useState } from "react";
import { Activity,AlertTriangle,BarChart3,CheckCircle2,Database,RefreshCw,ShieldCheck,Target } from "lucide-react";
import { Badge,SectionTitle } from "./ui";
import { cn } from "@/lib/utils";

type Metrics={tradeCount:number;winRatePct:number;expectancyPct:number;profitFactor:number;totalCompoundedReturnPct?:number;maxDrawdownPct:number;averageHoldingBars?:number;longTrades?:number;shortTrades?:number};
type Asset={currency:string;candles:number;from:string;to:string;full:{metrics:Metrics};holdout:{from:string;metrics:Metrics}};
type Report={strategy:{id:string;timeframe:string;minimumScore:number;breakoutBars:number;stopAtr:number;targetAtr:number;maxHoldingBars:number;cooldownBars:number};generatedAt:string;dataSource:string;executionModel:string;scope:string;assets:Asset[];promotion:{eligibleForTestnetForward:boolean;liveAuthorized:boolean;routingEnabled:boolean;status:string;metrics:Metrics;blockers:string[]}};

async function getReport(){const response=await fetch("/api/v1/autobot/swing-report",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error??"Swing report unavailable");return body as Report;}
const percent=(value:number)=>`${value>=0?"+":""}${value.toFixed(2)}%`;

export function StrategyCockpit(){
 const [report,setReport]=useState<Report|null>(null),[error,setError]=useState("");
 const load=useCallback(async()=>{try{setReport(await getReport());setError("");}catch(value){setError(value instanceof Error?value.message:"Swing report unavailable");}},[]);
 useEffect(()=>{const initial=setTimeout(()=>void load(),0);return()=>clearTimeout(initial);},[load]);
 if(!report)return <div className="panel flex h-80 items-center justify-center rounded-lg text-slate-400">{error||"Loading verified swing research…"}</div>;
 const gate=report.promotion,healthy=gate.eligibleForTestnetForward;
 return <div className="space-y-5">
  <section className="flex flex-col justify-between gap-4 border-b border-line/60 pb-5 sm:flex-row sm:items-end"><div><div className="font-mono text-[10px] uppercase tracking-[.22em] text-mint">Strategy research · non-routable</div><div className="mt-1 flex flex-wrap items-center gap-2"><h2 className="text-2xl font-semibold">Swing Trend Breakout</h2><Badge tone={healthy?"positive":"negative"}>{gate.status.replaceAll("_"," ")}</Badge><Badge tone="warning">ROUTING DISABLED</Badge></div><p className="mt-2 max-w-3xl text-xs leading-5 text-slate-300">A completed-candle {report.strategy.timeframe} BTC/ETH directional research strategy. Failed evidence cannot be activated from this page.</p></div><button onClick={()=>void load()} className="rounded border border-line px-4 py-2 text-[10px] text-slate-300"><RefreshCw className="mr-1 inline size-3"/>Refresh evidence</button></section>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Database} label="Combined sample" value={String(gate.metrics.tradeCount)} meta="closed proxy trades"/><Metric icon={Target} label="Expectancy / trade" value={percent(gate.metrics.expectancyPct)} meta="net of modeled costs" bad={gate.metrics.expectancyPct<=0}/><Metric icon={BarChart3} label="Profit factor" value={gate.metrics.profitFactor.toFixed(2)} meta="required ≥ 1.15" bad={gate.metrics.profitFactor<1.15}/><Metric icon={Activity} label="Worst drawdown" value={percent(-gate.metrics.maxDrawdownPct)} meta="limit 15%" bad={gate.metrics.maxDrawdownPct>15}/></div>
  <section className="panel overflow-hidden rounded-lg"><div className="border-b border-line px-5 py-4"><SectionTitle eyebrow="Two-year replay and recent-half check" title="Evidence by Asset" action={<span className="font-mono text-[9px] text-slate-400">{new Date(report.generatedAt).toLocaleString()}</span>}/></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="border-b border-line bg-black/20 text-[10px] uppercase text-slate-400"><tr><th className="px-5 py-3">Asset / window</th><th className="px-4 py-3">Trades</th><th className="px-4 py-3">Win rate</th><th className="px-4 py-3">Expectancy</th><th className="px-4 py-3">Profit factor</th><th className="px-4 py-3">Return</th><th className="px-5 py-3">Drawdown</th></tr></thead><tbody className="divide-y divide-line/60">{report.assets.flatMap(asset=>[[asset,"Full",asset.full.metrics],[asset,"Recent half",asset.holdout.metrics]] as const).map(([asset,window,metrics])=><tr key={`${asset.currency}-${window}`}><td className="px-5 py-4"><span className="font-mono font-semibold text-white">{asset.currency}</span><span className="ml-2 text-[10px] text-slate-400">{window}</span></td><Cell value={String(metrics.tradeCount)}/><Cell value={percent(metrics.winRatePct)}/><Cell value={percent(metrics.expectancyPct)} bad={metrics.expectancyPct<=0}/><Cell value={metrics.profitFactor.toFixed(2)} bad={metrics.profitFactor<1.15}/><Cell value={percent(metrics.totalCompoundedReturnPct??0)} bad={(metrics.totalCompoundedReturnPct??0)<0}/><Cell value={percent(-metrics.maxDrawdownPct)} bad={metrics.maxDrawdownPct>15}/></tr>)}</tbody></table></div></section>
  <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><section className="panel rounded-lg p-5"><SectionTitle eyebrow="Deterministic contract" title="Swing Policy"/><div className="grid gap-3 sm:grid-cols-2"><Datum label="Entry" value={`Fresh ${report.strategy.breakoutBars}-bar breakout · score ≥ ${report.strategy.minimumScore}`}/><Datum label="Execution" value="Next 6H bar open"/><Datum label="Risk / reward" value={`${report.strategy.stopAtr} ATR stop · ${report.strategy.targetAtr} ATR target`}/><Datum label="Maximum hold" value={`${report.strategy.maxHoldingBars} bars · ${Math.round(report.strategy.maxHoldingBars*6/24)} days`}/><Datum label="Cooldown" value={`${report.strategy.cooldownBars} bars · 1 day`}/><Datum label="Ambiguous bar" value="Stop evaluated before target"/></div><div className="mt-4 rounded border border-line bg-black/20 p-3 text-[10px] leading-5 text-slate-300">{report.executionModel}</div></section><section className="rounded-lg border border-coral/30 bg-coral/[.04] p-5"><SectionTitle eyebrow="Promotion decision" title="Blocked from Forward Test" action={<AlertTriangle className="size-4 text-coral"/>}/><div className="space-y-2">{gate.blockers.map(blocker=><div key={blocker} className="flex items-center gap-2 rounded border border-coral/20 p-3 font-mono text-[10px] text-coral"><AlertTriangle className="size-3.5"/>{blocker.replaceAll("_"," ")}</div>)}</div><div className="mt-4 flex items-center gap-2 text-[10px] text-slate-300"><ShieldCheck className="size-4 text-mint"/>Live authorized: NO · Testnet routing: OFF</div></section></div>
  <div className="rounded-lg border border-amber/25 bg-amber/[.04] p-4 text-[10px] leading-5 text-slate-300"><b className="text-amber">Evidence boundary:</b> {report.scope}. The replay uses underlying direction and does not model option IV, delta, theta decay, spreads, or strike liquidity. Its negative result is a hard blocker, not a profitability claim.</div>
 </div>;
}

function Metric({icon:Icon,label,value,meta,bad=false}:{icon:typeof Activity;label:string;value:string;meta:string;bad?:boolean}){return <div className="panel rounded-lg p-4"><div className="flex justify-between text-[10px] uppercase text-slate-400">{label}<Icon className={cn("size-4",bad?"text-coral":"text-mint")}/></div><div className={cn("mt-4 font-mono text-2xl font-semibold",bad?"text-coral":"text-white")}>{value}</div><div className="mt-1 text-[10px] text-slate-400">{meta}</div></div>}
function Cell({value,bad=false}:{value:string;bad?:boolean}){return <td className={cn("px-4 py-4 font-mono text-xs",bad?"text-coral":"text-slate-200")}>{value}</td>}
function Datum({label,value}:{label:string;value:string}){return <div className="rounded border border-line p-3"><div className="flex items-center gap-1 text-[9px] uppercase text-slate-400"><CheckCircle2 className="size-3 text-mint"/>{label}</div><div className="mt-2 font-mono text-[11px] text-slate-100">{value}</div></div>}
