"use client";
import { useCallback,useEffect,useState } from "react";
import { Activity,AlertTriangle,BarChart3,BrainCircuit,Database,RefreshCw,ShieldCheck,Target } from "lucide-react";
import { Badge,SectionTitle } from "./ui";
import { cn } from "@/lib/utils";

type Metrics={tradeCount:number;winRatePct?:number;expectancyPct:number;profitFactor:number;totalCompoundedReturnPct?:number;maxDrawdownPct:number;averageHoldingBars?:number};
type Fold={fold:number;trainFrom:string;trainTo:string;testFrom:string;testTo:string;selectedPolicy:{id:string;breakoutBars:number;stopAtr:number;targetAtr:number;maxHoldingBars:number};trainingMetrics:Metrics;testMetrics:Record<string,{tradeCount:number;expectancyPct:number;profitFactor:number}>};
type Report={strategy:{id:string;timeframe:string;selection:string;candidateCount:number};generatedAt:string;data:{source:string;from:string;to:string;candlesByAsset:Record<string,number>};directional:{executionModel:string;metrics:Metrics};optionsProxy:{model:string;feeModel:string;limitations:string[];metrics:Metrics&{signalTrades:number;rejectedTrades:number;averageEntryIvPct:number;averageSpreadPct:number}};folds:Fold[];promotion:{status:string;eligibleForTestnetForward:boolean;routingEnabled:boolean;liveAuthorized:boolean;blockers:string[]}};
type SnapshotQuality={contracts:number;twoSidedQuotes:number;ivCoveragePct:number;greeksCoveragePct:number;openInterestCoveragePct:number};
type SnapshotArchive={recorderOnline:boolean;status:{lastSnapshot?:string|null;nextSnapshot?:string|null;snapshotCount?:number;error?:string|null;latest?:{currencies:{currency:string;indexPrice:number;quality:SnapshotQuality}[]}|null};archive:{files:number;bytes:number;firstDate:string|null;lastDate:string|null};safety:{publicOnly:boolean;credentialsUsed:boolean;routingAvailable:boolean}};
const percent=(value:number)=>`${value>=0?"+":""}${value.toFixed(2)}%`;
async function getReport(){const response=await fetch("/api/v1/autobot/swing-report",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error??"Swing report unavailable");return body as Report;}
async function getSnapshotArchive(){const response=await fetch("/api/v1/autobot/option-snapshots",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error??"Snapshot archive unavailable");return body as SnapshotArchive;}

export function StrategyCockpit(){
 const [report,setReport]=useState<Report|null>(null),[archive,setArchive]=useState<SnapshotArchive|null>(null),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const [nextReport,nextArchive]=await Promise.all([getReport(),getSnapshotArchive()]);setReport(nextReport);setArchive(nextArchive);setError("");}catch(value){setError(value instanceof Error?value.message:"Research evidence unavailable");}},[]);
 useEffect(()=>{const initial=setTimeout(()=>void load(),0);return()=>clearTimeout(initial);},[load]);
 if(!report)return <div className="panel flex h-80 items-center justify-center rounded-lg text-slate-400">{error||"Loading walk-forward evidence…"}</div>;
 const directional=report.directional.metrics,options=report.optionsProxy.metrics;
 return <div className="space-y-5">
  <section className="flex flex-col justify-between gap-4 border-b border-line/60 pb-5 sm:flex-row sm:items-end"><div><div className="font-mono text-[10px] uppercase tracking-[.22em] text-mint">Rolling out-of-sample research · non-routable</div><div className="mt-1 flex flex-wrap items-center gap-2"><h2 className="text-2xl font-semibold">Regime Swing Walk-Forward</h2><Badge tone="negative">{report.promotion.status.replaceAll("_"," ")}</Badge><Badge tone="warning">ROUTING DISABLED</Badge></div><p className="mt-2 max-w-3xl text-xs leading-5 text-slate-300">The model selects a policy on prior data only, evaluates unseen BTC/ETH periods, then reprices each signal as an option with modeled IV, theta, spreads, fees and liquidity.</p></div><button onClick={()=>void load()} className="rounded border border-line px-4 py-2 text-[10px] text-slate-300"><RefreshCw className="mr-1 inline size-3"/>Refresh evidence</button></section>
  <SnapshotArchivePanel archive={archive}/>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Database} label="Out-of-sample signals" value={String(directional.tradeCount)} meta="required ≥ 30" bad={directional.tradeCount<30}/><Metric icon={Target} label="Directional expectancy" value={percent(directional.expectancyPct)} meta={`PF ${directional.profitFactor.toFixed(2)} · net costs`} bad={directional.profitFactor<1.15}/><Metric icon={BarChart3} label="Option proxy expectancy" value={percent(options.expectancyPct)} meta={`PF ${options.profitFactor.toFixed(2)} · modeled`} bad={options.maxDrawdownPct>25}/><Metric icon={Activity} label="Option proxy drawdown" value={percent(-options.maxDrawdownPct)} meta={`compounded ${percent(options.totalCompoundedReturnPct??0)}`} bad/></div>
  <section className="panel overflow-hidden rounded-lg"><div className="border-b border-line px-5 py-4"><SectionTitle eyebrow="Prior training only · following quarter unseen" title="Walk-Forward Folds" action={<span className="font-mono text-[9px] text-slate-400">{report.strategy.candidateCount} candidates · {new Date(report.generatedAt).toLocaleString()}</span>}/></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="border-b border-line bg-black/20 text-[10px] uppercase text-slate-400"><tr><th className="px-5 py-3">Fold</th><th className="px-4 py-3">Selected policy</th><th className="px-4 py-3">Training PF / Exp.</th><th className="px-4 py-3">BTC OOS</th><th className="px-4 py-3">ETH OOS</th><th className="px-5 py-3">Test window</th></tr></thead><tbody className="divide-y divide-line/60">{report.folds.map(fold=><tr key={fold.fold}><td className="px-5 py-4 font-mono text-white">{fold.fold}</td><td className="px-4 py-4"><div className="font-mono text-xs text-mint">{fold.selectedPolicy.id}</div><div className="mt-1 text-[9px] text-slate-400">{fold.selectedPolicy.breakoutBars} bar · {fold.selectedPolicy.stopAtr}/{fold.selectedPolicy.targetAtr} ATR · {fold.selectedPolicy.maxHoldingBars} max</div></td><Cell value={`${fold.trainingMetrics.profitFactor.toFixed(2)} / ${percent(fold.trainingMetrics.expectancyPct)}`}/><AssetCell value={fold.testMetrics.BTC}/><AssetCell value={fold.testMetrics.ETH}/><td className="px-5 py-4 font-mono text-[9px] text-slate-300">{new Date(fold.testFrom).toLocaleDateString()} – {new Date(fold.testTo).toLocaleDateString()}</td></tr>)}</tbody></table></div></section>
  <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><section className="panel rounded-lg p-5"><SectionTitle eyebrow="Options-aware model" title="IV, Theta, Spread & Fees" action={<BrainCircuit className="size-4 text-mint"/>}/><p className="text-[10px] leading-5 text-slate-300">{report.optionsProxy.model}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Datum label="Average entry IV" value={percent(options.averageEntryIvPct)}/><Datum label="Average modeled spread" value={percent(options.averageSpreadPct)}/><Datum label="Accepted / rejected" value={`${options.tradeCount} / ${options.rejectedTrades}`}/><Datum label="Fee model" value={report.optionsProxy.feeModel}/></div><div className="mt-4 rounded border border-coral/20 bg-coral/[.03] p-3 text-[10px] text-slate-300">Positive average option expectancy did not compound safely: sequence and magnitude of losses produced {percent(options.totalCompoundedReturnPct??0)} return and {percent(-options.maxDrawdownPct)} drawdown.</div></section><section className="rounded-lg border border-coral/30 bg-coral/[.04] p-5"><SectionTitle eyebrow="Promotion decision" title="Blocked" action={<AlertTriangle className="size-4 text-coral"/>}/><div className="max-h-[310px] space-y-2 overflow-auto">{report.promotion.blockers.map(blocker=><div key={blocker} className="flex items-center gap-2 rounded border border-coral/20 p-3 font-mono text-[9px] text-coral"><AlertTriangle className="size-3.5 shrink-0"/>{blocker.replaceAll("_"," ")}</div>)}</div><div className="mt-4 flex items-center gap-2 text-[10px] text-slate-300"><ShieldCheck className="size-4 text-mint"/>Forward Test: NO · Live: NO</div></section></div>
  <div className="rounded-lg border border-amber/25 bg-amber/[.04] p-4 text-[10px] leading-5 text-slate-300"><b className="text-amber">Model boundary:</b> {report.optionsProxy.limitations.join("; ")}. These results improve research quality but are not historical option execution evidence and cannot authorize trading.</div>
 </div>;
}

function Metric({icon:Icon,label,value,meta,bad=false}:{icon:typeof Activity;label:string;value:string;meta:string;bad?:boolean}){return <div className="panel rounded-lg p-4"><div className="flex justify-between text-[10px] uppercase text-slate-400">{label}<Icon className={cn("size-4",bad?"text-coral":"text-mint")}/></div><div className={cn("mt-4 font-mono text-2xl font-semibold",bad?"text-coral":"text-white")}>{value}</div><div className="mt-1 text-[10px] text-slate-400">{meta}</div></div>}
function Cell({value}:{value:string}){return <td className="px-4 py-4 font-mono text-xs text-slate-200">{value}</td>}
function AssetCell({value}:{value:{tradeCount:number;expectancyPct:number;profitFactor:number}}){return <td className="px-4 py-4"><div className={cn("font-mono text-xs",value.expectancyPct>=0?"text-mint":"text-coral")}>{percent(value.expectancyPct)}</div><div className="mt-1 text-[9px] text-slate-400">{value.tradeCount} trades · PF {value.profitFactor>=999?"∞":value.profitFactor.toFixed(2)}</div></td>}
function Datum({label,value}:{label:string;value:string}){return <div className="rounded border border-line p-3"><div className="text-[9px] uppercase text-slate-400">{label}</div><div className="mt-2 font-mono text-[10px] text-slate-100">{value}</div></div>}
function SnapshotArchivePanel({archive}:{archive:SnapshotArchive|null}){const latest=archive?.status.latest?.currencies??[];return <section className="panel rounded-lg p-5"><SectionTitle eyebrow="Observed Deribit Testnet market evidence" title="Read-Only Option Snapshot Archive" action={<Badge tone={archive?.recorderOnline?"positive":"negative"}>{archive?.recorderOnline?"RECORDER ONLINE":"RECORDER OFFLINE"}</Badge>}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Datum label="Snapshots" value={String(archive?.status.snapshotCount??0)}/><Datum label="Archive" value={`${archive?.archive.files??0} files · ${formatBytes(archive?.archive.bytes??0)}`}/><Datum label="Last observation" value={archive?.status.lastSnapshot?new Date(archive.status.lastSnapshot).toLocaleString():"Awaiting first snapshot"}/><Datum label="Safety boundary" value="PUBLIC ONLY · NO ROUTING"/></div>{latest.length>0&&<div className="mt-4 grid gap-3 lg:grid-cols-2">{latest.map(item=><div key={item.currency} className="rounded border border-line p-4"><div className="flex items-center justify-between"><span className="font-mono text-sm text-white">{item.currency} · ${item.indexPrice.toLocaleString()}</span><span className="text-[9px] text-slate-400">{item.quality.contracts} contracts</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-[9px] text-slate-300 sm:grid-cols-4"><span>Two-sided {item.quality.twoSidedQuotes}/{item.quality.contracts}</span><span>IV {item.quality.ivCoveragePct.toFixed(0)}%</span><span>Greeks {item.quality.greeksCoveragePct.toFixed(0)}%</span><span>OI {item.quality.openInterestCoveragePct.toFixed(0)}%</span></div></div>)}</div>}<div className="mt-4 flex items-center gap-2 text-[10px] text-slate-300"><ShieldCheck className="size-4 text-mint"/>No credentials, private endpoints, or trading methods are available to this recorder.{archive?.status.error&&<span className="text-coral"> Latest error: {archive.status.error}</span>}</div></section>}
function formatBytes(value:number){if(value<1024)return`${value} B`;if(value<1024*1024)return`${(value/1024).toFixed(1)} KB`;return`${(value/1024/1024).toFixed(1)} MB`;}
