"use client";

import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis, CartesianGrid } from "recharts";
import { markets } from "@/lib/mock-data";
import { cn } from "@/lib/utils";
import { SectionTitle } from "./ui";

const assets=["BTC","ETH","SOL","XRP","BNB","DOGE","LINK"];
const matrix=[[1,.89,.74,.62,.69,.58,.71],[.89,1,.81,.66,.74,.64,.78],[.74,.81,1,.52,.68,.71,.67],[.62,.66,.52,1,.58,.69,.48],[.69,.74,.68,.58,1,.55,.65],[.58,.64,.71,.69,.55,1,.51],[.71,.78,.67,.48,.65,.51,1]];
const divergence=Array.from({length:28},(_,i)=>({day:i+1,BTC:100+i*.68+Math.sin(i/3)*3.1,ETH:100+i*.85+Math.sin(i/3+.3)*4.2,spread:(i*.17)+Math.sin(i/4)*2}));
export function Markets(){return <div className="space-y-5"><div className="grid gap-5 xl:grid-cols-[1.1fr_1fr]"><section className="panel overflow-hidden rounded-lg p-5"><SectionTitle eyebrow="30-day returns" title="Cross-asset Correlation" action={<span className="font-mono text-[9px] text-slate-600">PEARSON · 1D CLOSE</span>}/><div className="grid min-w-[500px] grid-cols-8 gap-1 overflow-auto font-mono text-[9px]"><span/>{assets.map(a=><span key={a} className="grid h-7 place-items-center text-slate-500">{a}</span>)}{assets.map((row,i)=><div className="contents" key={row}><span className="grid place-items-center text-slate-500">{row}</span>{matrix[i].map((v,j)=><div key={j} className={cn("grid aspect-square place-items-center rounded border border-white/[.035]",i===j?"text-slate-700":"text-white")} style={{backgroundColor:i===j?"#11171c":v>=0?`rgba(35,247,182,${v*.42})`:`rgba(255,93,114,${Math.abs(v)*.42})`}}>{v.toFixed(2)}</div>)}</div>)}</div><div className="mt-4 flex items-center justify-center gap-3 font-mono text-[8px] text-slate-600"><span>-1.0</span><div className="h-1.5 w-40 rounded bg-gradient-to-r from-coral via-slate-800 to-mint"/><span>+1.0</span></div></section><section className="panel rounded-lg p-5"><SectionTitle eyebrow="Normalized performance" title="BTC vs ETH Divergence" action={<span className="font-mono text-[9px] text-amber">SPREAD +4.6σ</span>}/><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={divergence}><CartesianGrid stroke="#1c252d" vertical={false}/><XAxis dataKey="day" stroke="#35404a" fontSize={9}/><YAxis domain={[95,130]} stroke="#35404a" fontSize={9}/><Tooltip contentStyle={{background:"#0d1217",border:"1px solid #26313a",fontSize:10}}/><Line dataKey="BTC" stroke="#f6b94a" dot={false} strokeWidth={2}/><Line dataKey="ETH" stroke="#8197ff" dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></div><div className="flex justify-center gap-5 font-mono text-[9px]"><span className="text-amber">— BTC</span><span className="text-[#8197ff]">— ETH</span></div></section></div><section className="panel rounded-lg p-5"><SectionTitle eyebrow="Universe" title="Perpetual Markets"/><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{markets.map(m=><div key={m.symbol} className="flex items-center justify-between rounded border border-line/60 p-3"><div><b className="text-xs">{m.symbol}/USDT</b><div className="mt-1 text-[9px] text-slate-600">Funding {m.funding}%</div></div><div className="text-right font-mono"><div className="text-xs">${m.price}</div><div className={cn("text-[10px]",m.change>=0?"text-mint":"text-coral")}>{m.change>=0?"+":""}{m.change}%</div></div></div>)}</div></section></div>}
