"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, Calculator, LoaderCircle, Plus, RotateCcw, ShieldCheck, Trash2 } from "lucide-react";
import { Badge, SectionTitle } from "./ui";
import { cn } from "@/lib/utils";

type Currency = "BTC" | "ETH";
type OptionContract = { instrumentName:string; expirationTimestamp:number; strike:number; optionType:"call"|"put"; tickSize:number; minTradeAmount:number; bid_price:number|null; ask_price:number|null; mark_price:number|null; mark_iv:number|null; open_interest:number|null; underlying_price:number|null };
type Chain = { environment:"TESTNET"; currency:Currency; underlyingPrice:number|null; expiries:number[]; options:OptionContract[]; updatedAt:number };
type Status = { configured:boolean; authenticated:boolean; orderRouting:boolean; scope?:string };
type Leg = { instrumentName:string; type:"Call"|"Put"; side:"buy"|"sell"; strike:number; premium:number; ratio:number };
type Draft = { instrumentName:string; direction:"buy"|"sell"; price:number; amount:number };

async function jsonFetch<T>(url:string, init?:RequestInit):Promise<T> {
  const response=await fetch(url,{...init,headers:{"Content-Type":"application/json",...init?.headers}});
  const body=await response.json();
  if(!response.ok) throw new Error(body.message ?? body.error ?? `Request failed (${response.status})`);
  return body as T;
}

export function OptionsSuite() {
  const [currency,setCurrency]=useState<Currency>("BTC"); const [chain,setChain]=useState<Chain|null>(null); const [status,setStatus]=useState<Status|null>(null);
  const [expiry,setExpiry]=useState<number|null>(null); const [selected,setSelected]=useState<OptionContract|null>(null); const [ticker,setTicker]=useState<Record<string,unknown>|null>(null);
  const [draft,setDraft]=useState<Draft|null>(null); const [legs,setLegs]=useState<Leg[]>([]); const [amount,setAmount]=useState(.1); const [comboPrice,setComboPrice]=useState(0);
  const [ack,setAck]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");

  const load=useCallback(async()=>{try{const [nextChain,nextStatus]=await Promise.all([jsonFetch<Chain>(`/api/v1/deribit/chain?currency=${currency}`),jsonFetch<Status>("/api/v1/deribit/status")]);setChain(nextChain);setStatus(nextStatus);setExpiry(current=>nextChain.expiries.includes(current??-1)?current:nextChain.expiries[0]??null);}catch(error){setMessage(error instanceof Error?error.message:"Unable to load Deribit Testnet");}},[currency]);
  useEffect(()=>{const initial=setTimeout(()=>void load(),0);const timer=setInterval(()=>void load(),30_000);return()=>{clearTimeout(initial);clearInterval(timer);};},[load]);
  useEffect(()=>{if(!selected)return;let cancelled=false;jsonFetch<{ticker:Record<string,unknown>}>(`/api/v1/deribit/ticker?instrumentName=${encodeURIComponent(selected.instrumentName)}`).then(data=>{if(!cancelled)setTicker(data.ticker);}).catch(()=>setTicker(null));return()=>{cancelled=true;};},[selected]);

  const expiryOptions=useMemo(()=>chain?.options.filter(option=>option.expirationTimestamp===expiry)??[],[chain,expiry]);
  const rows=useMemo(()=>{const byStrike=new Map<number,{strike:number;call?:OptionContract;put?:OptionContract}>();expiryOptions.forEach(option=>{const row=byStrike.get(option.strike)??{strike:option.strike};row[option.optionType]=option;byStrike.set(option.strike,row);});const all=[...byStrike.values()].sort((a,b)=>a.strike-b.strike);const spot=chain?.underlyingPrice??0;const nearest=all.reduce((best,row,index)=>Math.abs(row.strike-spot)<Math.abs(all[best]?.strike-spot)?index:best,0);return all.slice(Math.max(0,nearest-8),nearest+9);},[expiryOptions,chain]);
  const chartData=useMemo(()=>rows.map(row=>({strike:row.strike,callOi:row.call?.open_interest??0,putOi:row.put?.open_interest??0,callIv:row.call?.mark_iv??null,putIv:row.put?.mark_iv??null})),[rows]);
  const putOi=expiryOptions.filter(x=>x.optionType==="put").reduce((sum,x)=>sum+(x.open_interest??0),0),callOi=expiryOptions.filter(x=>x.optionType==="call").reduce((sum,x)=>sum+(x.open_interest??0),0);
  const atm=expiryOptions.reduce<OptionContract|null>((best,x)=>!best||Math.abs(x.strike-(chain?.underlyingPrice??0))<Math.abs(best.strike-(chain?.underlyingPrice??0))?x:best,null);
  const maxPain=rows.reduce<{strike:number;oi:number}>((best,row)=>(row.call?.open_interest??0)+(row.put?.open_interest??0)>best.oi?{strike:row.strike,oi:(row.call?.open_interest??0)+(row.put?.open_interest??0)}:best,{strike:0,oi:-1}).strike;
  const payoff=useMemo(()=>{const spot=chain?.underlyingPrice??100;return Array.from({length:41},(_,i)=>{const price=spot*.65+i*spot*.0175;const pnl=legs.reduce((sum,leg)=>{const intrinsic=leg.type==="Call"?Math.max(0,price-leg.strike):Math.max(0,leg.strike-price);const premiumUsd=leg.premium*spot;return sum+(leg.side==="buy"?intrinsic-premiumUsd:premiumUsd-intrinsic)*leg.ratio*amount;},0);return{price,pnl};});},[legs,amount,chain]);

  function choose(option:OptionContract,direction:"buy"|"sell"){const raw=(direction==="buy"?option.ask_price:option.bid_price)??option.mark_price??option.tickSize;setSelected(option);setDraft({instrumentName:option.instrumentName,direction,price:roundTick(raw,option.tickSize),amount:option.minTradeAmount});setAck(false);setMessage("");}
  function addLeg(option:OptionContract){if(legs.some(leg=>leg.instrumentName===option.instrumentName)||legs.length>=4)return;setLegs(all=>[...all,{instrumentName:option.instrumentName,type:option.optionType==="call"?"Call":"Put",side:"buy",strike:option.strike,premium:option.mark_price??0,ratio:1}]);}
  async function orderAction(action:"preview"|"submit"){if(!draft)return;setBusy(true);setMessage("");try{const result=await jsonFetch<{result?:{order?:{order_id?:string}}}>("/api/v1/deribit/orders",{method:"POST",body:JSON.stringify({action,currency,...draft,idempotencyKey:crypto.randomUUID(),confirmTestnet:action==="submit"&&ack})});setMessage(action==="preview"?"Preview accepted. No order was sent.":`TESTNET order accepted${result.result?.order?.order_id?`: ${result.result.order.order_id}`:""}.`);if(action==="submit")setAck(false);}catch(error){setMessage(error instanceof Error?error.message:"Order rejected");}finally{setBusy(false);}}
  async function comboAction(action:"preview"|"submit"){setBusy(true);setMessage("");try{await jsonFetch("/api/v1/deribit/combos",{method:"POST",body:JSON.stringify({action,currency,direction:"buy",amount,price:comboPrice,idempotencyKey:crypto.randomUUID(),confirmTestnet:action==="submit"&&ack,legs:legs.map(leg=>({instrumentName:leg.instrumentName,direction:leg.side,ratio:leg.ratio}))})});setMessage(action==="preview"?"Atomic combo preview accepted. No combo or order was created.":"Atomic TESTNET combo order accepted.");if(action==="submit")setAck(false);}catch(error){setMessage(error instanceof Error?error.message:"Combo rejected");}finally{setBusy(false);}}

  if(!chain)return <div className="panel flex h-80 items-center justify-center rounded-lg text-slate-500"><LoaderCircle className="mr-2 size-4 animate-spin"/>Loading Deribit Testnet options…</div>;
  const greeks=(ticker?.greeks??{}) as Record<string,number>;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">Deribit Options</h2><Badge tone="positive">TESTNET LIVE</Badge>{status?<Badge tone={status.orderRouting?"positive":"warning"}>{status.orderRouting?"TESTNET ROUTING READY":"ROUTING LOCKED"}</Badge>:<Badge tone="warning">ROUTING CHECK…</Badge>}</div><p className="mt-1 text-[10px] text-slate-500">Public market data is live. Funds and orders are testnet-only.</p></div><div className="flex gap-2">{(["BTC","ETH"] as Currency[]).map(value=><button key={value} onClick={()=>{setCurrency(value);setLegs([]);setSelected(null);}} className={cn("rounded border px-4 py-2 font-mono text-[10px]",currency===value?"border-mint bg-mint/10 text-mint":"border-line text-slate-500")}>{value}</button>)}</div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label={`${currency} underlying`} value={money(chain.underlyingPrice)}/><Metric label="ATM mark IV" value={atm?.mark_iv?`${atm.mark_iv.toFixed(1)}%`:"—"}/><Metric label="Put / Call OI" value={callOi?(putOi/callOi).toFixed(2):"—"}/><Metric label="OI concentration" value={maxPain?money(maxPain):"—"}/></div>
    <section className="panel rounded-lg p-5"><SectionTitle eyebrow="Live chain · Deribit Testnet" title="Options Chain" action={<select value={expiry??""} onChange={e=>setExpiry(Number(e.target.value))} className="rounded border border-line bg-[#0d1217] px-3 py-1.5 font-mono text-[9px]">{chain.expiries.map(value=><option key={value} value={value}>{new Date(value).toLocaleDateString()}</option>)}</select>}/><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-center font-mono text-[9px]"><thead className="text-slate-600"><tr className="border-b border-line"><th className="py-2">CALL BID / ASK</th><th>CALL IV</th><th>CALL OI</th><th>STRIKE</th><th>PUT OI</th><th>PUT IV</th><th>PUT BID / ASK</th><th>ACTIONS</th></tr></thead><tbody>{rows.map(row=><tr key={row.strike} className={cn("border-b border-line/50",Math.abs(row.strike-(chain.underlyingPrice??0))<Math.max(row.strike*.015,1)&&"bg-amber/5")}><Cell option={row.call}/><td>{iv(row.call)}</td><td>{num(row.call?.open_interest)}</td><td className="py-2 text-amber">{money(row.strike)}</td><td>{num(row.put?.open_interest)}</td><td>{iv(row.put)}</td><Cell option={row.put}/><td><div className="flex justify-center gap-1">{row.call&&<button onClick={()=>choose(row.call!,"buy")} className="rounded bg-mint/10 px-2 py-1 text-mint">Buy C</button>}{row.put&&<button onClick={()=>choose(row.put!,"buy")} className="rounded bg-coral/10 px-2 py-1 text-coral">Buy P</button>}{row.call&&<button onClick={()=>addLeg(row.call!)} title="Add call to combo" className="rounded border border-line p-1"><Plus className="size-3"/></button>}{row.put&&<button onClick={()=>addLeg(row.put!)} title="Add put to combo" className="rounded border border-line p-1"><Plus className="size-3"/></button>}</div></td></tr>)}</tbody></table></div></section>
    <div className="grid gap-5 xl:grid-cols-2"><Chart title="Open Interest by Strike" data={chartData} kind="oi" spot={chain.underlyingPrice}/><Chart title="Implied Volatility Skew" data={chartData} kind="iv" spot={chain.underlyingPrice}/></div>
    {draft&&selected&&<section className="panel rounded-lg p-5"><SectionTitle eyebrow="Guarded single-leg ticket" title={selected.instrumentName} action={<Badge tone={status?.orderRouting?"positive":"warning"}>{status?.orderRouting?"TESTNET ROUTING READY":"ROUTING LOCKED"}</Badge>}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Field label="Direction"><select value={draft.direction} onChange={e=>setDraft({...draft,direction:e.target.value as "buy"|"sell"})} className="input"><option value="buy">BUY</option><option value="sell">SELL</option></select></Field><Field label="Limit price"><input type="number" step={selected.tickSize} value={draft.price} onChange={e=>setDraft({...draft,price:+e.target.value})} className="input"/></Field><Field label={`Amount (${currency})`}><input type="number" step={selected.minTradeAmount} value={draft.amount} onChange={e=>setDraft({...draft,amount:+e.target.value})} className="input"/></Field><Metric label="Delta" value={formatGreek(greeks.delta)}/><Metric label="Gamma" value={formatGreek(greeks.gamma)}/><Metric label="Vega" value={formatGreek(greeks.vega)}/></div><OrderActions busy={busy} routing={Boolean(status?.orderRouting)} ack={ack} setAck={setAck} preview={()=>void orderAction("preview")} submit={()=>void orderAction("submit")}/></section>}
    <div className="grid gap-5 xl:grid-cols-[1fr_1.15fr]"><section className="panel rounded-lg p-5"><SectionTitle eyebrow="2–4 leg native combo" title="Atomic Strategy Builder" action={<button onClick={()=>setLegs([])} className="text-slate-600 hover:text-white"><RotateCcw className="size-3.5"/></button>}/>{legs.length===0?<div className="rounded border border-dashed border-line p-8 text-center text-[10px] text-slate-600">Use + beside a live call or put to add a leg.</div>:<div className="space-y-2">{legs.map((leg,index)=><div key={leg.instrumentName} className="grid grid-cols-[1fr_56px_52px_28px] items-center gap-2 rounded border border-line p-2 font-mono text-[9px]"><span>{leg.instrumentName}</span><button onClick={()=>setLegs(all=>all.map((x,i)=>i===index?{...x,side:x.side==="buy"?"sell":"buy"}:x))} className={cn("rounded py-1",leg.side==="buy"?"bg-mint/10 text-mint":"bg-coral/10 text-coral")}>{leg.side}</button><input type="number" min="1" max="10" value={leg.ratio} onChange={e=>setLegs(all=>all.map((x,i)=>i===index?{...x,ratio:+e.target.value}:x))} className="input"/><button onClick={()=>setLegs(all=>all.filter((_,i)=>i!==index))}><Trash2 className="size-3 text-slate-600"/></button></div>)}</div>}<div className="mt-4 grid grid-cols-2 gap-3"><Field label={`Combo amount (${currency})`}><input type="number" value={amount} onChange={e=>setAmount(+e.target.value)} className="input"/></Field><Field label="Net limit price"><input type="number" value={comboPrice} onChange={e=>setComboPrice(+e.target.value)} className="input"/></Field></div><OrderActions busy={busy} routing={Boolean(status?.orderRouting&&legs.length>=2)} ack={ack} setAck={setAck} preview={()=>void comboAction("preview")} submit={()=>void comboAction("submit")}/></section><section className="panel rounded-lg p-5"><SectionTitle eyebrow="Estimate at expiration" title="Strategy Payoff" action={<Calculator className="size-4 text-slate-600"/>}/><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={payoff}><CartesianGrid stroke="#1c252d"/><XAxis dataKey="price" tickFormatter={v=>`${Math.round(v/1000)}k`} stroke="#35404a" fontSize={9}/><YAxis stroke="#35404a" fontSize={9}/><Tooltip contentStyle={{background:"#0d1217",border:"1px solid #26313a",fontSize:10}}/><ReferenceLine y={0} stroke="#586572"/><Area dataKey="pnl" stroke="#23f7b6" fill="#23f7b622" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></section></div>
    <div className={cn("flex items-start gap-2 rounded border p-3 text-[10px]",message?"border-amber/40 text-amber":"border-line text-slate-500")}><AlertTriangle className="mt-0.5 size-3.5 shrink-0"/><span>{message||(!status?.configured?"Add DERIBIT_TESTNET_CLIENT_ID and DERIBIT_TESTNET_CLIENT_SECRET to .env.local to unlock private testnet account and order features. Never use production credentials.":"No order is submitted by Preview. Submit requires the explicit TESTNET acknowledgement each time.")}</span></div>
  </div>;
}

function OrderActions({busy,routing,ack,setAck,preview,submit}:{busy:boolean;routing:boolean;ack:boolean;setAck:(v:boolean)=>void;preview:()=>void;submit:()=>void}){return <div className="mt-4 flex flex-wrap items-center gap-3"><button disabled={busy} onClick={preview} className="rounded border border-line px-4 py-2 font-mono text-[9px] disabled:opacity-40">Preview only</button><label className="flex items-center gap-2 text-[9px] text-slate-500"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/><ShieldCheck className="size-3 text-mint"/>I confirm this is Deribit TESTNET</label><button disabled={busy||!routing||!ack} onClick={submit} className="rounded bg-mint px-4 py-2 font-mono text-[9px] font-semibold text-black disabled:cursor-not-allowed disabled:opacity-30">{busy?"VALIDATING…":"SUBMIT TESTNET"}</button></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="panel rounded-lg p-4"><div className="text-[9px] uppercase text-slate-600">{label}</div><div className="mt-2 font-mono text-lg font-semibold">{value}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block [&_.input]:w-full [&_.input]:rounded [&_.input]:border [&_.input]:border-line [&_.input]:bg-black/20 [&_.input]:px-2 [&_.input]:py-2 [&_.input]:font-mono [&_.input]:text-[10px] [&_.input]:outline-none"><span className="mb-1 block text-[8px] uppercase text-slate-600">{label}</span>{children}</label>}
function Cell({option}:{option?:OptionContract}){return <td>{option?`${num(option.bid_price)} / ${num(option.ask_price)}`:"—"}</td>}
function Chart({title,data,kind,spot}:{title:string;data:Record<string,unknown>[];kind:"oi"|"iv";spot:number|null}){return <section className="panel rounded-lg p-5"><SectionTitle eyebrow="Selected expiry" title={title}/><div className="h-64"><ResponsiveContainer width="100%" height="100%">{kind==="oi"?<BarChart data={data}><CartesianGrid vertical={false} stroke="#1c252d"/><XAxis dataKey="strike" tickFormatter={v=>`${v/1000}k`} stroke="#35404a" fontSize={9}/><YAxis stroke="#35404a" fontSize={9}/><Tooltip contentStyle={{background:"#0d1217",border:"1px solid #26313a",fontSize:10}}/><Bar dataKey="callOi" fill="#23f7b6"/><Bar dataKey="putOi" fill="#ff5d72"/><ReferenceLine x={spot??0} stroke="#f6b94a"/></BarChart>:<AreaChart data={data}><CartesianGrid vertical={false} stroke="#1c252d"/><XAxis dataKey="strike" tickFormatter={v=>`${v/1000}k`} stroke="#35404a" fontSize={9}/><YAxis tickFormatter={v=>`${v}%`} stroke="#35404a" fontSize={9}/><Tooltip contentStyle={{background:"#0d1217",border:"1px solid #26313a",fontSize:10}}/><Area dataKey="callIv" stroke="#23f7b6" fill="#23f7b611"/><Area dataKey="putIv" stroke="#ff5d72" fill="#ff5d7211"/></AreaChart>}</ResponsiveContainer></div></section>}
function money(value:number|null|undefined){return value==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value)}
function num(value:number|null|undefined){return value==null?"—":value.toLocaleString(undefined,{maximumFractionDigits:4})}
function iv(value:OptionContract|undefined){return value?.mark_iv==null?"—":`${value.mark_iv.toFixed(1)}%`}
function formatGreek(value:number|undefined){return value==null?"—":value.toFixed(4)}
function roundTick(value:number,tick:number){const precision=Math.max(0,(String(tick).split(".")[1]??"").length);return Number((Math.round(value/tick)*tick).toFixed(precision))}
