"use client";

import { Activity, Crosshair, ScanSearch, Timer } from "lucide-react";
import { patterns, sparkline } from "@/lib/mock-data";
import { cn, formatPrice } from "@/lib/utils";
import { Badge, Progress, SectionTitle } from "./ui";
import { MiniChart } from "./mini-chart";

export function PatternScanner() {
  return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Status icon={ScanSearch} label="Charts scanned" value="2,472" meta="824 × 3 timeframes"/><Status icon={Activity} label="Active patterns" value="37" meta="12 high confidence"/><Status icon={Timer} label="Mean scan time" value="4.8s" meta="Last cycle 2s ago"/></div><section className="panel rounded-lg p-5"><SectionTitle eyebrow="Continuous recognition" title="Detected Chart Patterns" action={<Badge tone="positive">Scanner active</Badge>}/><div className="grid gap-4 md:grid-cols-2">{patterns.map((pattern,index)=><article key={pattern.id} className="overflow-hidden rounded-lg border border-line/70 bg-black/15"><div className="relative h-36 border-b border-line/50 p-4"><div className="absolute inset-0 opacity-60"><MiniChart data={sparkline.map((x,i)=> pattern.direction==="bullish" ? x+(index*4) : 120-x+i)} negative={pattern.direction==="bearish"} height={130}/></div><div className="absolute left-[24%] top-[34%] h-px w-[52%] -rotate-3 bg-amber/70"/><div className="absolute left-[28%] top-[70%] h-px w-[48%] rotate-3 bg-amber/70"/><Badge className="absolute left-3 top-3" tone={pattern.direction==="bullish"?"positive":"negative"}>{pattern.timeframe} · {pattern.direction}</Badge><div className="absolute bottom-2 right-3 font-mono text-[8px] text-slate-600"><Crosshair className="mr-1 inline size-3"/>AUTO ANNOTATED</div></div><div className="p-4"><div className="mb-4 flex items-start justify-between"><div><div className="text-sm font-semibold">{pattern.symbol}/USDT</div><div className="text-[10px] text-slate-500">{pattern.pattern} · {pattern.age}</div></div><div className="text-right"><div className="font-mono text-sm font-semibold">{pattern.progress}%</div><div className="text-[8px] uppercase tracking-wider text-slate-600">formed</div></div></div><Progress value={pattern.progress} tone={pattern.direction==="bullish"?"mint":"coral"}/><div className="mt-4 grid grid-cols-4 gap-2 font-mono"><Data label="Target" value={`$${formatPrice(pattern.target)}`} positive/><Data label="Stop" value={`$${formatPrice(pattern.stop)}`}/><Data label="R:R" value={`${pattern.rr}×`} positive/><Data label="Duration" value={pattern.timeframe==="1D"?"3–5d":"8–14h"}/></div></div></article>)}</div></section><section className="panel rounded-lg p-5"><SectionTitle eyebrow="Engine method" title="Detection Pipeline"/><div className="grid gap-2 sm:grid-cols-5">{["Pivot extraction","Trendline fitting","Shape validation","Breakout scoring","Target projection"].map((item,i)=><div key={item} className="relative rounded border border-line p-3"><span className="font-mono text-[9px] text-mint">0{i+1}</span><div className="mt-2 text-[11px]">{item}</div>{i<4&&<span className="absolute -right-2 top-1/2 z-10 hidden text-slate-700 sm:block">→</span>}</div>)}</div></section></div>;
}
function Status({icon:Icon,label,value,meta}:{icon:typeof ScanSearch;label:string;value:string;meta:string}) {return <div className="panel rounded-lg p-4"><div className="flex items-center justify-between"><div><div className="text-[10px] text-slate-500">{label}</div><div className="mt-2 font-mono text-2xl font-semibold">{value}</div><div className="mt-1 text-[9px] text-slate-700">{meta}</div></div><Icon className="size-6 text-mint/50" strokeWidth={1.4}/></div></div>}
function Data({label,value,positive}:{label:string;value:string;positive?:boolean}) {return <div><div className="text-[7px] uppercase tracking-wider text-slate-700">{label}</div><div className={cn("mt-1 text-[10px]",positive&&"text-mint")}>{value}</div></div>}
