"use client";
import { useCallback, useEffect, useState } from "react";
import { Activity, BellRing, Bot, Database, KeyRound, RefreshCw, Save, Server, ShieldCheck, Siren, TerminalSquare } from "lucide-react";
import { Badge, SectionTitle } from "./ui";
import { cn } from "@/lib/utils";

type Config={enabled:boolean;currencies:("BTC"|"ETH")[];minimumScore:number;maxPremiumUsd:number;maxDailyTrades:number;cooldownMinutes:number;stopLossPct:number;takeProfitPct:number};
type BotStatus={config:Config;state:{workerOnline:boolean;enabled?:boolean;exitManagementActive?:boolean;lastHeartbeat?:string;lastEvaluation?:string;positionCount?:number;openOrderCount?:number;error?:string|null};journal:unknown[];safety:{serverExecutionGate:boolean;productionRoutingAvailable:boolean}};
type DeribitStatus={environment:string;configured:boolean;authenticated:boolean;orderRouting:boolean;scope?:string};
type Health={status?:string;account?:{mode?:string;server?:string};safety?:{demoVerified?:boolean;realOrderRoutingAvailable?:boolean}};
type Preferences={engineAlerts:boolean;tradeAlerts:boolean;exitAlerts:boolean;sound:boolean};
const defaultPreferences:Preferences={engineAlerts:true,tradeAlerts:true,exitAlerts:true,sound:false};
async function getJson<T>(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{"Content-Type":"application/json"}});const body=await response.json();if(!response.ok)throw new Error(body.error??body.message??"Request failed");return body as T;}

export function SystemSettings(){
 const [bot,setBot]=useState<BotStatus|null>(null),[deribit,setDeribit]=useState<DeribitStatus|null>(null),[mt5,setMt5]=useState<Health|null>(null),[draft,setDraft]=useState<Config|null>(null),[prefs,setPrefs]=useState(defaultPreferences),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setBusy(true);try{const [nextBot,nextDeribit,nextMt5]=await Promise.all([getJson<BotStatus>("/api/v1/autobot/status"),getJson<DeribitStatus>("/api/v1/deribit/status"),getJson<Health>("/api/v1/mt5/health").catch(()=>null)]);setBot(nextBot);setDeribit(nextDeribit);setMt5(nextMt5);setDraft(current=>current??nextBot.config);}catch(error){setMessage(error instanceof Error?error.message:"Health check failed");}finally{setBusy(false);}},[]);
 useEffect(()=>{const initial=setTimeout(()=>{try{const saved=localStorage.getItem("cryptov2-notifications");if(saved)setPrefs({...defaultPreferences,...JSON.parse(saved)});}catch{}void load();},0);return()=>clearTimeout(initial);},[load]);
 function updatePrefs(next:Preferences){setPrefs(next);localStorage.setItem("cryptov2-notifications",JSON.stringify(next));setMessage("Notification preferences saved in this browser.");}
 async function savePolicy(){if(!draft||bot?.state.enabled)return;setBusy(true);try{const saved=await getJson<Config>("/api/v1/autobot/config",{method:"POST",body:JSON.stringify({...draft,enabled:false})});setDraft(saved);setMessage("Bot risk policy saved. Autonomous execution remains halted.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Policy rejected");}finally{setBusy(false);}}
 async function halt(){setBusy(true);try{await getJson("/api/v1/autobot/halt",{method:"POST"});setMessage("New entries paused. Existing bot-owned positions remain under automatic exit management.");await load();}finally{setBusy(false);}}
 if(!bot||!deribit||!draft)return <div className="panel flex h-80 items-center justify-center rounded-lg text-slate-500"><RefreshCw className="mr-2 size-4 animate-spin"/>Loading system settings…</div>;
 const active=Boolean(bot.state.enabled),locked=active;
 return <div className="space-y-5">
  <section className="flex flex-col justify-between gap-4 border-b border-line/60 pb-5 sm:flex-row sm:items-end"><div><div className="font-mono text-[9px] uppercase tracking-[.22em] text-mint">System administration</div><h2 className="mt-1 text-2xl font-semibold">Settings & Safety</h2><p className="mt-2 text-[10px] text-slate-500">Credentials are never returned to the browser. Only configuration status and granted scope are displayed.</p></div><button onClick={()=>void load()} disabled={busy} className="flex items-center gap-2 rounded border border-line px-4 py-2 text-[10px]"><RefreshCw className={cn("size-3.5",busy&&"animate-spin")}/>Refresh health</button></section>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Connection icon={Bot} label="AI worker" value={bot.state.workerOnline?"ONLINE":"OFFLINE"} detail={active?"Autonomous Testnet":"Monitoring / halted"} good={bot.state.workerOnline}/><Connection icon={KeyRound} label="Deribit API" value={deribit.authenticated?"AUTHENTICATED":"LOCKED"} detail={`${deribit.environment} · ${deribit.orderRouting?"trade scope ready":"read only"}`} good={deribit.authenticated}/><Connection icon={TerminalSquare} label="MT5 bridge" value={mt5?.status?.toUpperCase()??"UNAVAILABLE"} detail={mt5?.account?.server??"Optional integration"} good={mt5?.safety?.demoVerified}/><Connection icon={ShieldCheck} label="Production route" value={bot.safety.productionRoutingAvailable?"AVAILABLE":"NOT PRESENT"} detail="Deribit Testnet hard lock" good={!bot.safety.productionRoutingAvailable}/></div>
  <div className="grid gap-5 xl:grid-cols-[1fr_.8fr]"><section className="panel rounded-lg p-5"><SectionTitle eyebrow="Autonomous engine" title="Risk & Market Policy" action={<Badge tone={active?"warning":"positive"}>{active?"HALT TO EDIT":"EDITABLE"}</Badge>}/><div className="mb-4 flex gap-2">{(["BTC","ETH"] as const).map(currency=><button key={currency} disabled={locked} onClick={()=>setDraft({...draft,currencies:draft.currencies.includes(currency)?draft.currencies.filter(item=>item!==currency):[...draft.currencies,currency]})} className={cn("rounded border px-4 py-2 font-mono text-[9px] disabled:cursor-not-allowed disabled:opacity-50",draft.currencies.includes(currency)?"border-mint bg-mint/10 text-mint":"border-line text-slate-600")}>{currency}</button>)}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><NumberField label="Minimum signal score" value={draft.minimumScore} disabled={locked} onChange={value=>setDraft({...draft,minimumScore:value})}/><NumberField label="Maximum premium USD" value={draft.maxPremiumUsd} disabled={locked} onChange={value=>setDraft({...draft,maxPremiumUsd:value})}/><NumberField label="Trades per day" value={draft.maxDailyTrades} disabled={locked} onChange={value=>setDraft({...draft,maxDailyTrades:value})}/><NumberField label="Cooldown minutes" value={draft.cooldownMinutes} disabled={locked} onChange={value=>setDraft({...draft,cooldownMinutes:value})}/><NumberField label="Stop loss %" value={draft.stopLossPct} disabled={locked} onChange={value=>setDraft({...draft,stopLossPct:value})}/><NumberField label="Take profit %" value={draft.takeProfitPct} disabled={locked} onChange={value=>setDraft({...draft,takeProfitPct:value})}/></div><button onClick={savePolicy} disabled={busy||locked||draft.currencies.length===0} className="mt-4 flex w-full items-center justify-center gap-2 rounded bg-mint px-4 py-2.5 text-[10px] font-semibold text-black disabled:cursor-not-allowed disabled:opacity-30"><Save className="size-3.5"/>SAVE RISK POLICY</button>{locked&&<p className="mt-3 text-[9px] text-amber">Risk settings cannot change while autonomous execution is active. Use Emergency Halt first.</p>}</section>
  <section className="panel rounded-lg p-5"><SectionTitle eyebrow="Local preferences" title="Notifications" action={<BellRing className="size-4 text-mint"/>}/><div className="space-y-2"><Toggle label="Worker and engine alerts" checked={prefs.engineAlerts} onChange={value=>updatePrefs({...prefs,engineAlerts:value})}/><Toggle label="Autonomous entry alerts" checked={prefs.tradeAlerts} onChange={value=>updatePrefs({...prefs,tradeAlerts:value})}/><Toggle label="Exit and risk alerts" checked={prefs.exitAlerts} onChange={value=>updatePrefs({...prefs,exitAlerts:value})}/><Toggle label="Sound in this browser" checked={prefs.sound} onChange={value=>updatePrefs({...prefs,sound:value})}/></div><div className="mt-5 rounded border border-line p-3 text-[9px] leading-relaxed text-slate-600">These preferences are stored only in this browser. The active Codex position monitor remains independent.</div></section></div>
  <div className="grid gap-5 xl:grid-cols-[1fr_.8fr]"><section className="panel rounded-lg p-5"><SectionTitle eyebrow="Runtime & audit" title="Operational Information"/><div className="grid gap-3 sm:grid-cols-2"><Info icon={Server} label="Heartbeat" value={bot.state.lastHeartbeat?new Date(bot.state.lastHeartbeat).toLocaleString():"Unavailable"}/><Info icon={Activity} label="Last evaluation" value={bot.state.lastEvaluation?new Date(bot.state.lastEvaluation).toLocaleString():"Waiting"}/><Info icon={Database} label="Journal events loaded" value={String(bot.journal.length)}/><Info icon={ShieldCheck} label="Position / orders" value={`${bot.state.positionCount??0} / ${bot.state.openOrderCount??0}`}/></div><div className="mt-4 rounded border border-line bg-black/15 p-3 font-mono text-[9px] text-slate-500">Local runtime: D:\Projects\CryptoV2\work\autobot<br/>Launcher: D:\Projects\CryptoV2\Start-CryptoV2.bat</div></section>
  <section className="rounded-lg border border-coral/25 bg-coral/[.035] p-5"><SectionTitle eyebrow="Immediate safety control" title="Pause New Entries" action={<Siren className="size-4 text-coral"/>}/><p className="text-[10px] leading-relaxed text-slate-500">Blocks new autonomous entries while keeping stop-loss, take-profit, and opposite-signal exits active for existing bot-owned positions.</p><div className="mt-3"><Badge tone={bot.state.exitManagementActive?"positive":"warning"}>{bot.state.exitManagementActive?"EXIT MANAGEMENT ARMED":"EXIT MANAGEMENT UNAVAILABLE"}</Badge></div><button onClick={halt} disabled={busy||!active} className="mt-5 w-full rounded border border-coral/30 bg-coral/10 px-4 py-3 text-[10px] font-semibold text-coral disabled:opacity-30">PAUSE NEW AUTONOMOUS ENTRIES</button></section></div>
  {(message||bot.state.error)&&<div className={cn("rounded border p-3 text-[10px]",bot.state.error?"border-coral/30 text-coral":"border-mint/20 text-mint")}>{bot.state.error??message}</div>}
 </div>;
}
function Connection({icon:Icon,label,value,detail,good}:{icon:typeof Bot;label:string;value:string;detail:string;good?:boolean}){return <div className="panel rounded-lg p-4"><div className="flex justify-between text-[9px] uppercase text-slate-600">{label}<Icon className={cn("size-4",good?"text-mint":"text-amber")}/></div><div className={cn("mt-4 font-mono text-sm font-semibold",good?"text-mint":"text-amber")}>{value}</div><div className="mt-1 font-mono text-[8px] text-slate-600">{detail}</div></div>}
function NumberField({label,value,disabled,onChange}:{label:string;value:number;disabled:boolean;onChange:(value:number)=>void}){return <label className="text-[8px] uppercase text-slate-600">{label}<input type="number" value={value} disabled={disabled} onChange={event=>onChange(+event.target.value)} className="mt-1 w-full rounded border border-line bg-black/20 p-2 font-mono text-[10px] text-white outline-none disabled:opacity-40"/></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex items-center justify-between rounded border border-line p-3 text-[10px] text-slate-400"><span>{label}</span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)} className="accent-emerald-400"/></label>}
function Info({icon:Icon,label,value}:{icon:typeof Server;label:string;value:string}){return <div className="flex items-center gap-3 rounded border border-line p-3"><Icon className="size-4 text-mint"/><div><div className="text-[8px] uppercase text-slate-600">{label}</div><div className="mt-1 font-mono text-[9px]">{value}</div></div></div>}
