const BARS_PER_YEAR=365*4;
function normalCdf(value){const sign=value<0?-1:1,x=Math.abs(value)/Math.sqrt(2),t=1/(1+.3275911*x),erf=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-x*x);return.5*(1+sign*erf);}
export function blackScholes({spot,strike,timeYears,volatility,rate=.03,type}){if(timeYears<=0)return Math.max(0,type==="call"?spot-strike:strike-spot);const sigma=Math.max(.0001,volatility),sqrt=Math.sqrt(timeYears),d1=(Math.log(spot/strike)+(rate+.5*sigma*sigma)*timeYears)/(sigma*sqrt),d2=d1-sigma*sqrt;return type==="call"?spot*normalCdf(d1)-strike*Math.exp(-rate*timeYears)*normalCdf(d2):strike*Math.exp(-rate*timeYears)*normalCdf(-d2)-spot*normalCdf(-d1);}
export function optionDelta({spot,strike,timeYears,volatility,rate=.03,type}){if(timeYears<=0)return type==="call"?(spot>strike?1:0):(spot<strike?-1:0);const d1=(Math.log(spot/strike)+(rate+.5*volatility*volatility)*timeYears)/(volatility*Math.sqrt(timeYears));return type==="call"?normalCdf(d1):normalCdf(d1)-1;}
export function annualizedRealizedVol(close,endIndex,lookback=120){const start=Math.max(1,endIndex-lookback+1),returns=[];for(let index=start;index<=endIndex;index+=1)returns.push(Math.log(close[index]/close[index-1]));if(returns.length<20)return .7;const mean=returns.reduce((sum,value)=>sum+value,0)/returns.length,variance=returns.reduce((sum,value)=>sum+(value-mean)**2,0)/(returns.length-1);return Math.sqrt(variance*BARS_PER_YEAR);}
export function deribitOptionFeeUsd(spot,premiumUsd,amount=1){return Math.min(.0003*spot,.125*Math.max(0,premiumUsd))*amount;}
export function modelOptionTrade(trade,chart,{dte=45,ivMultiplier=1.15,minimumIv=.35,maximumIv=1.5}={}){const type=trade.direction===1?"call":"put",entrySpot=trade.entryPrice??chart.open[trade.entryIndex],exitSpot=trade.exitPrice??chart.close[trade.exitIndex],increment=entrySpot>10_000?1000:100,strike=Math.round(entrySpot/increment)*increment,holdingDays=trade.holdingBars*.25,remainingDte=Math.max(.25,dte-holdingDays),entryIv=Math.max(minimumIv,Math.min(maximumIv,annualizedRealizedVol(chart.close,trade.entryIndex)*ivMultiplier)),exitIv=Math.max(minimumIv,Math.min(maximumIv,annualizedRealizedVol(chart.close,trade.exitIndex)*ivMultiplier));
  const entryMid=blackScholes({spot:entrySpot,strike,timeYears:dte/365,volatility:entryIv,type}),exitMid=blackScholes({spot:exitSpot,strike,timeYears:remainingDte/365,volatility:exitIv,type}),spreadPct=Math.min(.18,.04+entryIv*.04+Math.max(0,30-dte)/1000),entryAsk=entryMid*(1+spreadPct/2),exitBid=Math.max(0,exitMid*(1-spreadPct/2)),entryFee=deribitOptionFeeUsd(entrySpot,entryAsk),exitFee=deribitOptionFeeUsd(exitSpot,exitBid),capital=entryAsk+entryFee,pnlUsd=exitBid-exitFee-capital,netReturnPct=capital?pnlUsd/capital*100:-100,liquid=entryMid/entrySpot>=.002&&entryMid/entrySpot<=.2&&spreadPct<=.15;
  return{...trade,type,strike,dte,remainingDte,entrySpot,exitSpot,entryIv,exitIv,entryMid,entryAsk,exitMid,exitBid,entryFee,exitFee,spreadPct,entryDelta:optionDelta({spot:entrySpot,strike,timeYears:dte/365,volatility:entryIv,type}),pnlUsd,netReturnPct,liquid,rejectionReason:liquid?null:"MODELED_LIQUIDITY_GATE"};}
export function summarizeOptionTrades(trades){const accepted=trades.filter(trade=>trade.liquid),wins=accepted.filter(trade=>trade.netReturnPct>0).length,grossProfit=accepted.filter(trade=>trade.netReturnPct>0).reduce((sum,trade)=>sum+trade.netReturnPct,0),grossLoss=-accepted.filter(trade=>trade.netReturnPct<0).reduce((sum,trade)=>sum+trade.netReturnPct,0);let equity=1,peak=1,maxDrawdownPct=0;for(const trade of accepted){equity*=Math.max(.0001,1+trade.netReturnPct/100);peak=Math.max(peak,equity);maxDrawdownPct=Math.max(maxDrawdownPct,(peak-equity)/peak*100);}return{signalTrades:trades.length,tradeCount:accepted.length,rejectedTrades:trades.length-accepted.length,wins,losses:accepted.length-wins,winRatePct:accepted.length?wins/accepted.length*100:0,expectancyPct:accepted.length?accepted.reduce((sum,trade)=>sum+trade.netReturnPct,0)/accepted.length:0,profitFactor:grossLoss?grossProfit/grossLoss:grossProfit?Infinity:0,totalCompoundedReturnPct:(equity-1)*100,maxDrawdownPct,averageEntryIvPct:accepted.length?accepted.reduce((sum,trade)=>sum+trade.entryIv*100,0)/accepted.length:0,averageSpreadPct:accepted.length?accepted.reduce((sum,trade)=>sum+trade.spreadPct*100,0)/accepted.length:0};}
